# Generated by Django 4.0.5 on 2022-06-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourFullNmae', models.CharField(max_length=100)),
                ('YourEmail', models.CharField(max_length=100)),
                ('YourPhone', models.IntegerField()),
                ('QueryTopic', models.CharField(max_length=100)),
                ('YourMessage', models.CharField(max_length=200)),
            ],
        ),
    ]
