# Generated by Django 4.0.5 on 2022-06-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='YourMessage',
            field=models.TextField(max_length=200),
        ),
    ]
