# Generated by Django 4.0.3 on 2022-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singupmodel',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
