# Generated by Django 4.0.5 on 2022-06-26 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingUp', '0003_alter_singupmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singupmodel',
            name='Brith_Date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
